### PR TITLE
add training GQA

### PR DESCRIPTION
**Pull request by beatrizserrano**

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks!

@gmauro please have a look at those. Maybe I also don't see some failures.

**Comment by bgruening** [comment]
Danke @beatrizserrano

**Comment by gmauro** [comment]
We have only 8 c.c32m240 hosts and in any case, there is no need to assign more than 1 or 2 hosts per training. I never saw a training job running into a training host, they are always managed by regular hosts.

**Comment by beatrizserrano** [comment]
what do we do then in cases like this?

**Comment by gmauro** [comment]
The hosts are created at midnight of the start day and destroyed at midnight+1m of the end day.
You can change the number on the fly at any time, every 4 hours a cron job update accordingly the infrastructure

**Comment by beatrizserrano** [comment]
mmm what I mean is: if the resources requested result in more than 8 hosts, do we assign only those 8?

**Comment by gmauro** [comment]
Training jobs use regular hosts and training host together. Don't imagine all the jobs of the training need to be supported by training hosts only

**Comment by gmauro** [comment]
Training hosts are there mainly to manage the case when the main cluster is full, but also in that (remote) situation, it means to wait a few minutes.

**Pull request merged**
