### PR TITLE
Add new dnb-ds01 and dnb-ds02 mount points

### PR DESCRIPTION
**Pull request by sanjaysrikakulam**
Adds the missing mounts via the `userdata.yml` to `/etc/auto.data`.

### CODE REVIEW

**Comment by sj213** [comment]
It took me some time to realize that the PR's commit is not in a branch of `vgcn-infrastructure` but in a different repo altogether (had to have a checkout so I could view the vault-file in cleartext). The definitions of the new mount points look just fine; I'm not approving yet because one of the automated checks has failed. What exactly caused the "Validate"-check to fail is unclear to me.

**Comment by sanjaysrikakulam** [comment]
Thank you @sj213. I am not sure what this "validate" is trying, it's totally unclear to me too.

**Comment by sj213** [comment]
I don't understand the "validate" check either. Maybe @bgruening can shed some light on this? (Some of these checks have strange idiosyncrasies; e.g. YAML-lint barfs on trailing newlines, whoda thunk it...? But this is not lint.)

**Comment by bgruening** [comment]
So unrelated to the PR, but I guess I broke the resource.yml file on master.

**Comment by sanjaysrikakulam** [comment]
Sorry, I will fix it. I will close this PR. Found conflicts. I will create a new PR from the main branch.

**Pull request closed without merging**
