### PR TITLE
add training 2020-04-22-sbc

### PR DESCRIPTION
**Pull request by beatrizserrano**

### CODE REVIEW

**Comment by beatrizserrano** [comment]
@gmauro I've seen in the email generated that the cost is 0 and realised that `c.c32m240` is missing [here](https://github.com/usegalaxy-eu/vgcn-infrastructure/blob/master/cost.py), could you have a look? Thanks!

**Comment by bgruening** [comment]
We figured out the error, its a OSX "feature". So this script only works on GNU systems.

**Comment by beatrizserrano** [comment]
Alles gut hier? 😄

**Comment by bgruening** [comment]
Oh yes, I have an email in my inbox asking for this.

**Pull request merged**
