### PR TITLE
Add new dnb-ds01 and dnb-ds02 mount points

### PR DESCRIPTION
**Pull request by sanjaysrikakulam**
Adds the missing mounts via the userdata.yml to /etc/auto.data

### CODE REVIEW

**Comment by sanjaysrikakulam** [comment]
Sorry for the last PR confusion. My fork missed the `main` branch and went to `maste`r as default.

**Comment by sj213** [comment]
After de-crypting the previous and the proposed version and running `diff -u` on them I noticed the following changes:

1. Indentation of the list under `write_files:` has changed

This is ok by YAML syntax and looks better but made comparison difficult, so I undid the indentation change on a temp copy of the file (`1,$ s/^  //`) and found the following changes:

2. Mount points added:
   - `dnb-ds01`
   - `dnb-ds02`
   - `jwd02f`
   - `jwd03f`
   - `jwd04`

3. Mount points changed:
   -  `jwd01`: removed `nconnect` parameter (which is neccessary only for Netapp-shares)

4. String values of `permissions:` changed quoting from single to double

Looks ok by me, approving.

**Review by sj213 — APPROVED** [review]
Looks ok by me (see my comment in conversations)

**Comment by bgruening** [comment]
Cool thanks, everyone!

**Comment by sanjaysrikakulam** [comment]
> After de-crypting the previous and the proposed version and running `diff -u` on them I noticed the following changes:
> 
> 1. Indentation of the list under `write_files:` has changed
> 
> This is ok by YAML syntax and looks better but made comparison difficult, so I undid the indentation change on a temp copy of the file (`1,$ s/^ //`) and found the following changes:
> 
> 2. Mount points added:
>    
>    * `dnb-ds01`
>    * `dnb-ds02`
>    * `jwd02f`
>    * `jwd03f`
>    * `jwd04`
> 3. Mount points changed:
>    
>    * `jwd01`: removed `nconnect` parameter (which is neccessary only for Netapp-shares)
> 4. String values of `permissions:` changed quoting from single to double
> 
> Looks ok by me, approving.

All I added were two lines (new mount points dnb-dd01 and dnb-ds02). The file from the other PR is probably old and was missing quite a few things that's why you see so many differences.

**Comment by sj213** [comment]
I just now realized that at some point the HEAD ptr must have changed from `master` to `main` but I'd just done `git pull` to update my copy, so I probably missed those changes by culling my "original" file from the wrong branch. I guess that explains all the extra "changes" I saw...

**Pull request merged**
