### PR TITLE
Add rsyslog configuration file and rsyslog restart

### PR DESCRIPTION
**Pull request by kysrpex**
Let's try this way?

```
- content: |
      *.info;mail.none;authpriv.none;cron.none @@10.5.68.158:514
    owner: root:root
    path: /etc/rsyslog.d/remote.conf
    permissions: "0644"
runcmd:
  - 'systemctl restart rsyslog.service'
```

Follow-up of #207.

### CODE REVIEW

**Comment by kysrpex** [comment]
I suggest to restart one of the stuck VMs after merging this to test it.

**Comment by mira-miracoli** [comment]
are you sure the quotes work? I did not find it in the docks:
https://cloudinit.readthedocs.io/en/latest/reference/examples.html#run-commands-on-first-boot
(at least not latest version)
I think you could drop them

**Comment by kysrpex** [comment]
> are you sure the quotes work? I did not find it in the docks: https://cloudinit.readthedocs.io/en/latest/reference/examples.html#run-commands-on-first-boot (at least not latest version) I think you could drop them

I have seen them in other examples and, provided that cloud-init has a proper YAML parser, quotes and no quotes should mean the same. I think they should work but I also think you're right about being able to drop them and I am just paranoid. Anyway I'll merge and restart a single stuck VM to see the outcome.

**Comment by sanjaysrikakulam** [comment]
FYI: Restarting a VM will not run the cloudinit stuff. It runs only once when you create a VM.

**Comment by kysrpex** [comment]
> FYI: Restarting a VM will not run the cloudinit stuff. It runs only once when you create a VM.

Sorry I was using colloquial language. I understand that I need to recreate it.

**Comment by mira-miracoli** [comment]
Let's try

**Review by mira-miracoli — APPROVED** [review]

**Pull request merged**
