### PR TITLE
I don't think we use those VMs anymore.

### PR DESCRIPTION
**Pull request by bgruening**
However, I guess we need to switch to TPV at first.

### CODE REVIEW

**Comment by kysrpex** [comment]
It does not look to me like we are using `fast-turnaround` either.

**Comment by kysrpex** [comment]
@mira-miracoli @sanjaysrikakulam Anything against removing those VMs? The primary cluster will keep a minimum of 1 VM in all groups unless we chose to dedicate a fraction of absolutely zero resources to the primary, so removing groups we do not need would free up some resources.

**Comment by bgruening** [comment]
+1

**Comment by bgruening** [comment]
Lol, thats my PR ... ok, so its does not really count :)

**Review by sanjaysrikakulam — APPROVED** [review]
Thank you!

**Pull request merged**
