### PR TITLE
Add training york

### PR DESCRIPTION
**Pull request by beatrizserrano**
@gmauro I have split the training into 4 individual days, but made up the training ids, is that ok? There will be also 4 different URLs, one per day.

### CODE REVIEW

**Comment by bgruening** [comment]
I guess 4 URLs is totally fine.

**Comment by gmauro** [comment]
Yeah, that's okay. Probably I could implement a "start-array" and 'end-array" option.
Day 2 has a number of nodes completely different from others, is it wanted?

**Comment by beatrizserrano** [comment]
No, not wanted, the number of attendees is constant and so should be the number of nodes. It's just based on the limitation of 9 nodes for training. There are already 2 trainings on that day: `training-gqa` (4) and `training-debr` (4). Should I distribute the nodes in a more balanced way? Maybe worth increasing the number of training nodes in anticipation of the semester?

**Comment by gmauro** [comment]
Maybe a 3-3-3 schema?

**Pull request merged**
